### ISSUE TITLE
[Bug] Doesn't include simple tag based style declarations in output.css file 

### ISSUE THREAD

**Issue by KRTirtho** [tiny-css/compiler#1]
This compiler only generates style declarations based on classes defined in the JSON file. Doesn't seem to be appending the tag based declarations in the output stylesheet.
```css
:root {
    --blue: #007bff;
    --indigo: #6610f2;
    --purple: #6f42c1;
    --pink: #e83e8c;
    --red: #dc3545;
    --orange: #fd7e14;
    --yellow: #ffc107;
    --green: #28a745;
    --teal: #20c997;
    --cyan: #17a2b8;
}
*,
*::before,
*::after {
    box-sizing: border-box;
}

html {
    font-family: sans-serif;
    line-height: 1.15;
    -webkit-text-size-adjust: 100%;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
article,
aside,
figcaption,
figure,
footer,
header,
hgroup,
main,
nav,
section {
    display: block;
}
@keframes animate{
  0%{
  color: red;
  },
  100%{
  color:pink;
  }
}
```  
This kind of selectors are ignored but they should be included in the stylesheet also
